### PR TITLE
Typer Class Enhancments

### PR DESCRIPTION
**Pull request by AdamSGit**
Refer to issue #34
The Typer Class has been greatly improved in term of control. 

## Let's start with breaking changes : 

The duration parameter has become two new ones : speed and pause
  * speed is the elapsed time between the animation of each characters of a text (Default is 40 ms)
  * pause is the pause duration between texts (Default is 500 ms)

## New features : 

Three new callbacks come alongside the onTap :  
  * onNext(int index, bool isLast) - This callback will be called before the next text animation, after the previous one's pause. 
  * onNextBeforePause(int index, bool isLast) - This callback will be called before the next text animation, before the previous one's pause. 
  * onFinished - This callback is called at the end, if the parameter isRepeatingAnimation is set to false

Two new arguments : 
  * displayFullTextOnTap - If true, tapping the screen will stop current animated text, and display it fully for min(remaining, pause) time. (Default is false)
  * stopPauseOnTap - If true, tapping during a pause will stop it and start the next text animation (Default is false)

The text list parameter now accept either strings, or map where you can give a text custom speed and pause.

---

If you like thoses changes, I'll make another commit with updated readme regarding this PR with code examples.

### CODE REVIEW

**Comment by AdamSGit** [comment]
Ok, I recreated a fresh pull request in the correct repo. Also I created a v2 branch on this one so others possible changes can be  made in this branch before merging.

**Comment by aagarwal1012** [comment]
@AdamSGit, this PR looks good. Travis CI failed due to bad formatting, please fix that.

**Comment by AdamSGit** [comment]
The [travis report](https://travis-ci.com/aagarwal1012/Animated-Text-Kit/jobs/238105894) isn't quite explanatory. I'm confused on what is the problem here.

**Comment by AdamSGit** [comment]
Ok fixed it. Now this codecov thing doesn't really show where the coverage changes happened. Do you see anything ?

**Comment by aagarwal1012** [comment]
@AdamSGit, this is because you haven't wrote any `tests` for the changes that you have made.

**Comment by AdamSGit** [comment]
Oh, I see. Will write them. For doc and example, we can wait to have to changes ported to others texts.

**Comment by aagarwal1012** [comment]
@AdamSGit do you got any updates for us?

**Comment by AdamSGit** [comment]
Hi @aagarwal1012 
Worked on other stuff lately. Will try to get it done as soon as possible.
Cheer

**Comment by aagarwal1012** [comment]
@allcontributors add @AdamSGit for feature enhancement and improving the package.

**Comment by aagarwal1012** [comment]
@allcontributors add @AdamSGit for ideas and maintaining the package.

**Pull request merged**
