### PR TITLE
TickerProvider -> Singletickerprovider

### PR DESCRIPTION
**Pull request by SirusCodes**
Did changes in fade, rotate and scale. Thanks to @awhitford for fixing `Timer` issues😊
Issue number #119

### CODE REVIEW

**Review by awhitford — APPROVED** [review]
LGTM.  Note that I did not run this code -- just reviewed it.

**Comment by SirusCodes** [comment]
It was running on my device(Android).

**Review by aagarwal1012 — APPROVED** [review]
lgtm

**Comment by aagarwal1012** [comment]
@SirusCodes, thanks for your contribution. I have sent you a collaborator invite, hope to see more contributions from you.

**Comment by SirusCodes** [comment]
Thanks a lot😊💙

**Pull request merged**
