### PR TITLE
Add Wavy Animation

### PR DESCRIPTION
**Pull request by SirusCodes**
Hey, kindly have a look at it. I have completed Wavy Animation. Issue - #106

### CODE REVIEW

**Comment by SirusCodes** [comment]
@AadumKhor @aagarwal1012 @hemilpanchiwala review it please

**Comment by AadumKhor** [comment]
Hi @SirusCodes the checks are failing due to formatting. Please run `flutter format .` from the AnimatedTextKit folder.

**Comment by SirusCodes** [comment]
Did it @AadumKhor

**Review by AadumKhor — APPROVED** [review]

**Comment by AadumKhor** [comment]
@aagarwal1012 I think there are no issues. Readme is also updated. You can proceed with the merge.

**Review by aagarwal1012 — APPROVED** [review]
@AadumKhor thanks for reviewing this PR.

**Comment by aagarwal1012** [comment]
@allcontributors add @SirusCodes for ideas, code, design and docs.

**Pull request merged**
