### PR TITLE
Added note about Fade customization.

### PR DESCRIPTION
**Pull request by awhitford**
Just added note to `CHANGELOG` about new feature to customize the Fade animation.

### CODE REVIEW

**Comment by aagarwal1012** [comment]
lgtm

**Review by aagarwal1012 — APPROVED** [review]
lgtm

**Comment by aagarwal1012** [comment]
@awhitford, I think you forgot to push `v4.1.0` to [pub.dev](pub.dev).

**Comment by awhitford** [comment]
@aagarwal1012 I was merely _setting up the publish_ -- I figured that someone else (like you) would make the decision to publish 4.1.0.

**Comment by aagarwal1012** [comment]
@awhitford, I have no words to say 😅. I can publish `v4.1.0` for now, but you have full freedom to take any decision for the `Animated Text Kit` package.

**Comment by awhitford** [comment]
Thank you.  Sometimes with _radical changes_, I like to pause for feedback in case there is something controversial or unexpected.

**Pull request merged**
