### PR TITLE
bfix: Unhandled Exception: setState() called after dispose() in ScaleAnimatedTextKit

### PR DESCRIPTION
**Pull request by asionbo**
Check the "mounted" property before calling setState()

### CODE REVIEW

**Comment by H4llJ0rdan** [comment]
I need this bug fix. Can someone please merge it?

**Review by awhitford — APPROVED** [review]
I must admit that I do not totally understand why these empty `setState` calls are being made. However, this makes _scale_ consistent with the others.

**Comment by awhitford** [comment]
The build failed because it failed the _dart format_ test.

**Comment by awhitford** [comment]
I submitted #143 to replace this PR; the new one passes the build test.

@asionbo In the future, I highly recommend using the _Format on Save_ feature to ensure conformant formatted code. This project is strict because it rejects code that isn't formatted as expected.

**Comment by awhitford** [comment]
Please note that this fix is part of the **2.5.2** release.

**Pull request closed without merging**
