### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by awhitford**

### CODE REVIEW

**Review by aagarwal1012 — APPROVED** [review]
Great work @awhitford 💯

**Comment by awhitford** [comment]
@aagarwal1012 Hold on please...

**Comment by aagarwal1012** [comment]
@awhitford now you can release `v3.0.0` on pub.dev, after that I will do a GitHub version release.

**Comment by awhitford** [comment]
@aagarwal1012 While writing the `README` updates, I might have stumbled across a subtle issue that needs to be clarified...

I am not 100% clear on the semantics of the `isRepeatingAnimation`, `repeatForever`, and `totalRepeatCount` properties.  I tried to simply carry forward existing logic, but I may have added an invalid assertion.  I generally like to see assertions point out invalid configurations, and these properties are sometimes mutually exclusive.  For example, `totalRepeatCount` is ignored (or invalid?) when `repeatForever` is `true`.

https://github.com/aagarwal1012/Animated-Text-Kit/blob/cda8190fcb991459e493f525def431a2bf5c6467/lib/src/animated_text.dart#L102-L139

Specifically:
```dart
         assert(repeatForever || null != totalRepeatCount), 
```
Is this _sound_?  Or should we consider `isRepeatingAnimation` as well?
Are there other assertions that we should consider?

**Comment by awhitford** [comment]
In other words...
* May `repeatForever` only be `true` when `isRepeatingAnimation` is also `true`?
* May `totalRepeatCount` only be _non-null_ when `isRepeatingAnimation` is `true` and `repeatForever` is `false`?

**Comment by awhitford** [comment]
And when does `onFinished` apply?  I am now thinking that this:
```dart
         assert(null == onFinished || !isRepeatingAnimation), 
```
should really be:
```dart
         assert(null == onFinished || !repeatForever), 
```

**Comment by aagarwal1012** [comment]
> - May `repeatForever` only be true when `isRepeatingAnimation` is also true?
> - May `totalRepeatCount` only be non-null when `isRepeatingAnimation` is true and `repeatForever` is false?

@awhitford, the current implementation is fine for this one, when `repeatForever` is true then we should ignore `isRepeatingAnimation` parameter, Else we should consider `isRepeatingAnimation` value.

> And when does `onFinished` apply?

I agree with the suggestion of changing it to `assert(null == onFinished || !repeatForever),`.

**Comment by aagarwal1012** [comment]
@awhitford, please do a `rebase` before merging this PR 😁

**Comment by awhitford** [comment]
> > * May `repeatForever` only be true when `isRepeatingAnimation` is also true?
> > * May `totalRepeatCount` only be non-null when `isRepeatingAnimation` is true and `repeatForever` is false?
> 
> @awhitford, the current implementation is fine for this one, when `repeatForever` is true then we should ignore `isRepeatingAnimation` parameter, Else we should consider `isRepeatingAnimation` value.

```dart
         assert(repeatForever || null != totalRepeatCount), 
```

My problem with this is that it suggests that `totalRepeatCount` must be specified when `repeatForever` is `false`.  That does not seem sound.  I honestly think that when I wrote this, I had forgotten about `isRepeatingAnimation`.  I think it should be:

```dart
         assert(!isRepeatingAnimation || null != totalRepeatCount || repeatForever);
```

_What do you think?_

> I agree with the suggestion of changing it to `assert(null == onFinished || !repeatForever),`.

Done. ✅

**Comment by aagarwal1012** [comment]
> `assert(!isRepeatingAnimation || null != totalRepeatCount || repeatForever);`
This assertion makes totally sense 👍

**Pull request merged**
