### PR TITLE
Added pedantic lint rules.

### PR DESCRIPTION
**Pull request by awhitford**
This enables a bunch of wise rules for `flutter analyze` and helps promote code quality.

Note that there is a [minor bug](https://github.com/dart-lang/pedantic/issues/72) where `include_file_not_found` is erroneously reported, but the rules are still being checked.

### CODE REVIEW

**Comment by awhitford** [comment]
The erroneous `include_file_not_found` has been resolved.

**Comment by awhitford** [comment]
Is the build breaking because of the analyze results?  Or is there something else going on?

**Comment by aagarwal1012** [comment]
@awhitford, `pedantic` introduced some flutter analysis issues that need to be fixed for this PR. Logs are given below:
```dart
Analyzing 3 directories...                                      
   info • Private field could be final • lib/src/colorize.dart:96:13 • prefer_final_fields
   info • Omit type annotations for local variables • lib/src/colorize.dart:141:17 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/colorize.dart:162:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/fade.dart:201:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/fade.dart:232:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/fade.dart:258:9 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/rotate.dart:249:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/rotate.dart:280:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/scale.dart:226:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/scale.dart:257:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/scale.dart:283:9 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/text_liquid_fill.dart:189:10 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/typer.dart:165:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/typer.dart:200:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/typewriter.dart:179:17 • omit_local_variable_types
   info • Only use double quotes for strings containing single quotes • lib/src/typewriter.dart:181:35 • prefer_single_quotes
   info • Omit type annotations for local variables • lib/src/typewriter.dart:212:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/typewriter.dart:253:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/wavy.dart:123:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/wavy.dart:156:5 • omit_local_variable_types
   info • Private field could be final • lib/src/wavy.dart:175:25 • prefer_final_fields
   info • Use isEmpty instead of length • lib/src/wavy.dart:179:9 • prefer_is_empty
   info • DO use curly braces for all flow control structures • lib/src/wavy.dart:185:7 • curly_braces_in_flow_control_structures
   info • Omit type annotations for local variables • lib/src/wavy.dart:185:12 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/wavy.dart:191:11 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/wavy.dart:229:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/wavy.dart:230:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/wavy.dart:231:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/wavy.dart:232:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/wavy.dart:233:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/wavy.dart:273:5 • omit_local_variable_types
   info • Omit type annotations for local variables • lib/src/wavy.dart:280:10 • omit_local_variable_types
   info • Avoid relative imports for files in `lib/` • test/smoke_test.dart:3:8 • avoid_relative_lib_imports
```

**Comment by awhitford** [comment]
I didn't realize those warning would break the build.  I fixed all but one with #133.  Does the build need to have zero?

**Comment by aagarwal1012** [comment]
@awhitford, every build needs to have zero warnings in order to pass the tests.

**Comment by awhitford** [comment]
I'm unclear how to best resolve the last one:  [avoid_relative_lib_imports](https://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html).
https://github.com/aagarwal1012/Animated-Text-Kit/blob/5b78fa01a3f900d1ad8319d8bb7de3439594979e/test/smoke_test.dart#L3

**Comment by awhitford** [comment]
@aagarwal1012 OK, it's ready now.

**Review by aagarwal1012 — APPROVED** [review]
lgtm

**Pull request merged**
