### PR TITLE
feat: add repeat forever option

### PR DESCRIPTION
**Pull request by yiminghan**
## Pull Request Process

1. Ensure any install or build dependencies are removed before the end of the layer when doing a build.
2. Update the README.md if needed with details of changes to the interface, this includes new environment variables, exposed ports, useful file locations and container parameters.
3. Increase the version numbers in any examples files and the README.md to the new version that this Pull Request would represent. The versioning scheme we use is [SemVer](http://semver.org/).
4. You may merge the Pull Request in once you have the sign-off of one developer, or if you do not have permission to do that, you may request the second reviewer to merge it for you.

### CODE REVIEW

**Comment by aagarwal1012** [comment]
@AadumKhor, this PR looks good to me. Can you also share your opinions?

**Comment by AadumKhor** [comment]
@aagarwal1012 I was going to address this issue in my next PR. My approach however was removing the count factor when `isRepeatingAnimation` is true i.e. repeating the animation forever without involving any additional parameter since I agree with what is suggested in #66 .

I like the approach used in this PR as well since it maintains the way our package is used currently and at the same time allows more customization. Personally I like the former approach since repeating animation is this particular use case should not be restricted by count. Also this might help in resolving #52 since we are not keeping track of count anymore which might be causing the problem.

**Comment by yiminghan** [comment]
@AadumKhor My main consideration here is that there's no unexpected breaking changes for current users, since if we change the behaviour of `isRepeatingAnimation` it's going to require a lot of existing users to change their code.

**Comment by aagarwal1012** [comment]
@yiminghan, your argument seems right to me. @AadumKhor, should I merge this PR and make a new release?

**Comment by AadumKhor** [comment]
@aagarwal1012 We can add this to the new release as suggested.

**Comment by aagarwal1012** [comment]
@all-contributors, add @yiminghan for feature enhancement.

**Comment by aagarwal1012** [comment]
@allcontributors, add @yiminghan for feature enhancement.

**Comment by aagarwal1012** [comment]
@all-contributors, add @AadumKhor as maintainer of this package.

**Comment by aagarwal1012** [comment]
@allcontributors add @yiminghan for feature enhancement.

**Comment by aagarwal1012** [comment]
@allcontributors add @yiminghan for Ideas & Planning.

**Pull request merged**
