### PR TITLE
Add Feature in TypewriterAnimatedKit allowing users to have variable typing speed.

### PR DESCRIPTION
**Pull request by ayagrwl**
## Pull Request Process

1. Ensure any install or build dependencies are removed before the end of the layer when doing a build.
2. Update the README.md if needed with details of changes to the interface, this includes new environment variables, exposed ports, useful file locations and container parameters.
3. Increase the version numbers in any examples files and the README.md to the new version that this Pull Request would represent. The versioning scheme we use is [SemVer](http://semver.org/).
4. You may merge the Pull Request in once you have the sign-off of one developer, or if you do not have permission to do that, you may request the second reviewer to merge it for you.

By taking an Additional `curves` parameter in the input, i made the typing speed (which was linear), follow the variable speed provided by the curve (In the TypewriterAnimationKit). Updated README and formatted code. Please build the example code to see the new animation. My favourite curve is the Curves.bounceIn 😁😁.

### CODE REVIEW

**Comment by ayagrwl** [comment]
I too was looking forward to adding it to others if this was accepted. will do it now ✌️

**Comment by ayagrwl** [comment]
Is there an issue on my part that this PR is not yet merged ?

**Comment by awhitford** [comment]
I noticed that the `State` classes have their own `_curve` copy, but I do not see that it is necessary because the value never changes from the `widget.curve`.  Can those be removed?

Also, since these classes have been modified recently, there are now merge conflicts.  Perhaps rebasing will help.

**Comment by ayagrwl** [comment]
Sure. I will update the pr within a week.

**Comment by ayagrwl** [comment]
It seems like the code structure has changed a lot since i forked. Also, @AbhayVAshokan has added this curve feature to typer and typewriter animations (refer [commit](https://github.com/aagarwal1012/Animated-Text-Kit/commit/095576b3c404ae7628c7c33df410f4ba9ab7204a))
I am not very familiar with using git, so i think I will re-fork, commit my changes there, and create a new PR to add this curve feature in scale, liquid_fill, and rotate animations.

**Comment by SirusCodes** [comment]
> It seems like the code structure has changed a lot since i forked. Also, @AbhayVAshokan has added this curve feature to typer and typewriter animations (refer [commit](https://github.com/aagarwal1012/Animated-Text-Kit/commit/095576b3c404ae7628c7c33df410f4ba9ab7204a))
> I am not very familiar with using git, so i think I will re-fork, commit my changes there, and create a new PR to add this curve feature in scale, liquid_fill, and rotate animations.

You have also commited it from your master branch, always create a new branch for any contribution

**Comment by SirusCodes** [comment]
@ayagrwl are you working on it?

**Comment by ayagrwl** [comment]
@SirusCodes I apologize for abandoning without notification. Please close this issue as I wont be working on it anymore. Even if I happen to implement this feature (if its not done until), I'll fork a fresh copy of the repo, and create a separate pull request.

**Comment by SirusCodes** [comment]
> @SirusCodes I apologize for abandoning without notification. Please close this issue as I wont be working on it anymore. Even if I happen to implement this feature (if its not done until), I'll fork a fresh copy of the repo, and create a separate pull request.

Thanks for working on it. I understand that you might have some other responsibilities. Closing this 😞

**Pull request closed without merging**
