### PR TITLE
Upgraded pedantic and resolved the sort_child_properties_last lint issue.

### LINKED ISSUE #199: CI broken with Flutter 2 - sort_child_properties_last
It appears that the code is failing the `flutter analyze` check, which is breaking the CI builds.  This seems to be since Flutter 2.  See [sort_child_properties_last](https://dart-lang.github.io/linter/lints/sort_child_properties_last.html).

### PR DESCRIPTION
**Pull request by awhitford**
Resolves #199.

### CODE REVIEW

**Comment by awhitford** [comment]
@aagarwal1012 Please update the project settings so that the `stable` channel is _Required_ (not the `beta` channel) -- since Flutter 2 has finally been released.

**Comment by awhitford** [comment]
See how `nnbd` raised the _code coverage_ because it doesn't have as many `assert` lines that do not count as covered.
(It isn't this PR that boosted the code coverage, but this PR enabled the new score to be published.)

**Comment by SirusCodes** [comment]
NNBD helped us to increase our code coverage 😆 great!

**Comment by aagarwal1012** [comment]
@awhitford, I have updated the branch protection rule -- now we are good to go. 👍

**Pull request merged**
