### PR TITLE
[docs] Added flutter favorite badge to Readme

### PR DESCRIPTION
**Pull request by aagarwal1012**
Hey everyone, 

`animated_text_kit` has been chosen as a Flutter Favorite Package 🎉🎉, this would not have been possible without you. Special thanks to @awhitford @SirusCodes @hemilpanchiwala @AadumKhor for maintaining the package when I wasn't available. 😇

cc: @AbhayVAshokan @nakjemmy @aniketambore @aliyoge @r1walz @yiminghan @AdamSGit @anderscheow 

image

### CODE REVIEW

**Comment by SirusCodes** [comment]
This is amazing 😍 congratulations everyone!!!!

**Comment by AadumKhor** [comment]
Congratulations everyone! So glad to be a part of this 🔥

**Comment by anderscheow** [comment]
Thanks all! Can't imagine I can be part of it, feels so proud! Time to add this into my portfolio. ❤️

**Comment by awhitford** [comment]
Excellent news!  I'm happy to help and appreciate the team's enthusiastic support.  Congratulations everyone!

**Comment by hemilpanchiwala** [comment]
Excellent! It's been a great feeling to hear this. Congrats everyone!

**Pull request merged**
