### PR TITLE
Added support to disable cursor in typewriter

### PR DESCRIPTION
**Pull request by darrendavidhumphrey**
Added support to change cursor character in typewriter

## Pull Request Process

1. Ensure any install or build dependencies are removed before the end of the layer when doing a build.
2. Update the README.md if needed with details of changes to the interface, this includes new environment variables, exposed ports, useful file locations and container parameters.
3. Increase the version numbers in any examples files and the README.md to the new version that this Pull Request would represent. The versioning scheme we use is [SemVer](http://semver.org/).
4. You may merge the Pull Request in once you have the sign-off of one developer, or if you do not have permission to do that, you may request the second reviewer to merge it for you.

### CODE REVIEW

**Comment by aagarwal1012** [comment]
@darrendavidhumphrey, 
- [ ] Please fix the formatting issues by running the command `flutter format .` 
- [ ] Also, add docs related to the new parameter that you introduced in the Typewriter section of Readme.

**Comment by AadumKhor** [comment]
@darrendavidhumphrey please make the required changes to the Readme so that we can move forward with this PR.

**Comment by darrendavidhumphrey** [comment]
Hi Aayush,

It's unclear what you would like me to do. I added some examples to the
main readme. Is there another readme I missed?

Darren

**Comment by AadumKhor** [comment]
@aagarwal1012 would you mind resolving conflicts for this PR? I guess this is good to go.

**Comment by aagarwal1012** [comment]
Sure, I will do it today whenever I get some time!

**Comment by aagarwal1012** [comment]
@darrendavidhumphrey, can you please resolve merge conflicts?

**Comment by darrendavidhumphrey** [comment]
Interesting, the conflicts are in a footer section that I didn't modify.  I
am not sure which version is correct, so I can't merge it for you.

**Comment by awhitford** [comment]
I like the option of overriding the cursor character.

However, if someone wants to hide the cursor, could they simply specify a space as the cursor character OR use the `TyperAnimatedTextKit` class?

**Comment by aagarwal1012** [comment]
Closing this PR, rework required!

**Comment by awhitford** [comment]
> I like the option of overriding the cursor character.

See PR #230 -- the `cursor` can now be _overridden_.

If you want to _hide_ the cursor, I highly recommend just using `Typer` instead of `Typewriter`.  However, you can also specify an _empty string_ or a _space_ as the cursor.

**Pull request closed without merging**
